### ISSUE TITLE
A question about the demo online of Huggingface Space 

### ISSUE THREAD

**Issue by Weistrass** [yu-rp/apiprompting#2]
Excuse me, I find there is only the version of CLIP apiprompting on the Huggingface Space demo online. What about the version of LLaVA？I also want to try the version of LLaVA. Thanks!

**Comment by yu-rp** [comment]
Hi @Weistrass , thank you for your issue.

Due to the memory and storage limitations of the free version of HuggingFace Spaces, we are unable to deploy the LLaVA version on it. You may try the code [here](https://github.com/yu-rp/apiprompting/tree/master/demo) and run it locally. There is an option that allows you to switch between the CLIP version and the LLaVA version.

**Comment by Weistrass** [comment]
Thanks, I will have a try. Have a good day!
